ALTER TABLE `Geolocations`
	DROP PRIMARY KEY;
ALTER TABLE `Geolocations`
	ADD COLUMN `ID` INT(11) NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (`ID`);
ALTER TABLE `Geolocations`
	DROP FOREIGN KEY `FK_Geolocations_Items`;
ALTER TABLE `Geolocations`
	ADD CONSTRAINT `FK_Geolocations_Items` FOREIGN KEY (`ItemID`) REFERENCES `Items` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE;